create table if not exists USER (ID INT IDENTITY PRIMARY KEY ,
  USERNAME VARCHAR(255) NOT NULL ,
  EMAIL VARCHAR(255) NOT NULL ,
  BIO VARCHAR(255) ,
  IMAGE VARCHAR(255) ,
  PASSWORD VARCHAR(255) NOT NULL ,
  PASSWORD_SALT VARCHAR(255));
